### ISSUE TITLE
Allerletzte Karte im Spiel kann nicht gespielt werden

### ISSUE THREAD

**Issue by janKir** [wizard-online/wizard-online#47]
Offenbar tritt ein Fehler beim Beenden des Spiels durch das Spielen der letzten Karte auf.

**Comment by janKir** [comment]
Konnte ich gerade nicht reproduzieren. Vielleicht wurde es durch einen der letzten beiden PRs bereits gefixt. Sollten wir aber mal im Auge behalten in den nächsten Tests.

**Comment by janKir** [comment]
```
    TypeError: Cannot perform 'IsArray' on a proxy that has been revoked

      at hasBinary (node_modules/has-binary2/index.js:35:7)
      at hasBinary (node_modules/has-binary2/index.js:58:59)
      at hasBinary (node_modules/has-binary2/index.js:58:59)
      at hasBinary (node_modules/has-binary2/index.js:37:11)
      at Socket.Object.<anonymous>.Socket.emit (node_modules/socket.io/lib/socket.js:148:66)
      at send (node_modules/boardgame.io/dist/server.js:4300:44)
      at node_modules/boardgame.io/dist/server.js:4331:9
          at Set.forEach (<anonymous>)
      at Object.sendAll (node_modules/boardgame.io/dist/server.js:4325:26)
      at Master.onUpdate (node_modules/boardgame.io/dist/server.js:4170:27)
      at Socket.<anonymous> (node_modules/boardgame.io/dist/server.js:4380:28)
      at node_modules/socket.io/lib/socket.js:528:12
```

**Comment by janKir** [comment]
Der Fehler ist entstanden durch den Aufruf des `endGame` Events. Diesem Event kann man ein Argument mitgeben, dass daraufhin unter `ctx.gameover` abgerufen werden kann. Wird hier allerdings ein Object verwendet, dass aus dem Game-State kommt, verursacht dies den serverseitigen Fehler.
